### ISSUE TITLE
[Bug] Remote操作時の意図しない挙動

### ISSUE THREAD

**Issue by itigopasuta** [dash-app/dash-home#17]
## What/Why - 問題の説明

- NewController画面でtypeがREMOTEである。
- Vendorの処理で範囲外をクリックした場合、本来消えないはずの画面が消える。

## How - どのような対応が必要ですか？
- Vendorの処理をSwitchBotの処理と同様に消えない設定を行う。
***
[//]: # (必要に応じてスクリーンショットやログなどを提示するのを推奨します。)

**Comment by Laica-Lunasys** [comment]
2箇所でTypoしているのが原因
https://github.com/dash-app/dash-home/blob/wip/frontend/frontend/dash-home/src/components/controller/RemoteChooser.tsx#L40

https://github.com/dash-app/dash-home/blob/wip/frontend/frontend/dash-home/src/components/controller/RemoteChooser.tsx#L60

**Comment by Laica-Lunasys** [comment]
下記PRにて修正済み
https://github.com/dash-app/dash-home/pull/18
